server:
  port: ${API_PORT:8080}

spring:
  application:
    name: festmap
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:festmap}
    username: ${DB_USER:festmap}
    password: ${DB_PASSWORD:password}
    hikari:
      initialization-fail-timeout: -1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

logging:
  level:
    '[com.zaxxer.hikari]': INFO
    '[net.ttddyy.dsproxy]': INFO
    org:
      springframework:
        jdbc:
          core: DEBUG
          JdbcTemplate: DEBUG
          StatementCreatorUtils: TRACE
springdoc:
  packages-to-scan:
    - com.project.festmap.festival.api
    - com.project.festmap.shared.api
    - com.project.festmap.user.api
  swagger-ui:
    path: /swagger-ui.html

app:
  cors:
    allowed-origins: http://localhost:4200
  jwt:
    secret: ${JWT_SECRET:c3VwZXItc2VjcmV0LWtleS1mb3Itand0LXNlY3VyaXR5LXRoYXQtbXVzdC1iZS1sb25nLWVub3VnaA==}
    expiration: 86400000 # 24 hours
