server:
    port: ${SERVER_PORT:8080}

spring:
    application:
        name: festmap
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DB_URL:jdbc:postgresql://${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}}
        username: ${DB_USERNAME:${POSTGRES_USER}}
        password: ${DB_PASSWORD:${POSTGRES_PASSWORD}}
        hikari:
            initialization-fail-timeout: -1
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yml

logging:
    level:
        '[com.zaxxer.hikari]': INFO
        '[net.ttddyy.dsproxy]': INFO
        org:
            springframework:
                jdbc:
                    core: DEBUG
                    JdbcTemplate: DEBUG
                    StatementCreatorUtils: TRACE